Global seed set to 1583745484
parameter settings:
n_queries: 2
model: vgg19
savedir: exp/cifar10/victim
mode: eval
Files already downloaded and verified
train_ds:  40000
[18185, 41944, 39282, 35090, 30503, 37898, 49682, 5070, 17288, 14716, 27746, 14457, 45275, 27329, 6398, 24717, 28517, 5449, 44227, 934, 33016, 2112, 7675, 38181, 36293, 33067, 43471, 3154, 44400, 35927, 45604, 32716, 47179, 29338, 25746, 24013, 530, 19828, 31087, 49422, 8789, 37956, 894, 656, 8106, 28795, 17464, 33634, 18551, 37903, 31826, 18537, 13433, 15847, 23692, 20023, 24416, 16293, 26603, 30737, 34462, 1503, 23259, 9152, 4855, 9669, 6359, 5161, 6961, 7239, 13233, 16339, 40159, 31209, 41990, 5144, 38440, 4303, 38968, 49158, 33167, 39765, 39572, 31680, 15996, 34983, 41059, 10597, 41393, 28344, 47303, 42900, 21500, 37800, 10169, 19032, 41641, 36964, 43093, 20237]
eval_ds:  10000
[47321, 25975, 49276, 45119, 39574, 12954, 4957, 7644, 6614, 2424, 16309, 12644, 3330, 30453, 15570, 7966, 14869, 7448, 1670, 8269, 44622, 23739, 45798, 26781, 30963, 23444, 21783, 11690, 24685, 9146, 48985, 12115, 8865, 9276, 31157, 14575, 10611, 1096, 32458, 45212, 21540, 24110, 26118, 42056, 35655, 15495, 16425, 41446, 49064, 15124, 34228, 10106, 3304, 2982, 46634, 45550, 3704, 44513, 35831, 7334, 17803, 49534, 28406, 898, 31782, 68, 40417, 28926, 32848, 38180, 48853, 21182, 11802, 24373, 24536, 40022, 46944, 25008, 36690, 23574, 20191, 14503, 18477, 35770, 28887, 661, 25271, 3079, 40520, 45551, 6295, 43924, 39592, 38765, 43550, 21244, 11381, 49885, 12746, 28850]
Traceback (most recent call last):
  File "inference.py", line 147, in <module>
    run()
  File "/home/dsanyal7/miniconda3/envs/mia/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "inference.py", line 67, in run
    elif arg.smode == "eval":
AttributeError: 'str' object has no attribute 'smode'
